### ISSUE TITLE
Not compatible with Google Chrome "as is"

### ISSUE THREAD

**Issue by rossanx** [factrylabs/grafana-replay-controls#1]
I've tested with google-chrome and Firefox. It works out-of-the-box with Firefox, but not with chrome. I haven't changed any google-chrome configuration to try to make it work. So, I believe it's still possible to make it work with google-chrome with some tweaking.

**Comment by coussej** [comment]
Working in chrome: https://demo.factry.io/d/ZhjweprWk/city-water-tank-flowchart
