### ISSUE TITLE
Alignment of Icons has been shifted at Grafana 8

### ISSUE THREAD

**Issue by YutaSuzu** [factrylabs/grafana-replay-controls#2]
Thank you for your great controls.

When I use Grafana 8.3
Alignment of "backward icon" and other of icon has been shifted.

![image](https://user-images.githubusercontent.com/42123485/156292066-398d9119-d68a-4391-a2af-7f2f457de907.png)

Would you able to fix?

**Comment by coussej** [comment]
Probably related to sizing of panel, looks fine [here](https://demo.factry.io/d/ZhjweprWk/city-water-tank-flowchart). Closing.
