### ISSUE TITLE
Working ?

### ISSUE THREAD

**Issue by skreu** [factrylabs/grafana-replay-controls#3]
Hi, I'm on Grafana 10.4.0 ans PostgreSQL and it appears that the plugin is not working. The tile is appearing nice and smooth but when I click on play nothing happens

**Comment by skreu** [comment]
Hi!

When i click to play / pause, i get an error of variable used before Assignment...
On the demo, there is a deprecation warning in grafana 10.2.0. Can't understand why in mine it's not working...
Any help appreciated here !

Have a nice day !

**Comment by skreu** [comment]
Able to solved de variable used before assignment by changing "let" to "var". But got a "can't find variable : angular" ! ^^'

**Comment by coussej** [comment]
Hi there! From what I can see on the demo, it's working on grafana 10.2 (see the [demo](https://demo.factry.io/d/ZhjweprWk/city-water-tank-flowchart)), in both chrome & firefox. 

When you say it's not working when you push the forward or backward button, what exactly is happening? The timestamps are not changing at all? Please paste your specific error and the conditions in which occured (browser, ...).

Closing until more info.

**Comment by skreu** [comment]
Hi,
Thank you for your answer. The Demo version also works for me... but not mine...

I'm running  Grafana v10.4.0. I did everything mentionned in the readme :
1. disabling sanitizing html
2.  adding a text panel
3. setting html to it
4. pasting the content

The controls buttons apeears as intended but... when i click nothing happens...
Either on edge, firefox, safari, chrome i get two or three errors:
1. is on loading page

```
Uncaught ReferenceError: angular is not defined
    at <anonymous>:3:17
    at index.js:22:20
    at Mf (react-dom.production.min.js:244:332)
    at Es (react-dom.production.min.js:286:111)
    at el (react-dom.production.min.js:273:185)
    at va (react-dom.production.min.js:127:105)  
    at Ca (react-dom.production.min.js:283:470)  
    at Oa (react-dom.production.min.js:281:398)  
    at Ad (react-dom.production.min.js:270:269)  
    at T (scheduler.production.min.js:13:203)
```

2. is when i click on whatever fast forward, reverse
``` 
Uncaught ReferenceError: Cannot access 'reverse' before initialization
    at play (<anonymous>:9:13)
    at HTMLButtonElement.onclick (live-drive?orgId=1&refresh=5s:1:1)
```

or play_button
``` 
Uncaught ReferenceError: Cannot access 'play_mode' before initialization
    at pause (<anonymous>:17:15)
    at HTMLButtonElement.onclick (live-drive?orgId=1&refresh=5s:1:1)
```

or change the time interval
``` 
Uncaught ReferenceError: play_interval is not defined
    at HTMLSelectElement.onchange (live-drive?orgId=1&refresh=5s:1:15)
```

and the third one is when i just go in the panel menu (where i can modify things), if i just go there and back the third error is : 
``` 
Uncaught SyntaxError: Identifier 'timeSrv' has already been declared
    at index.js:22:20
    at Mf (react-dom.production.min.js:244:332)
    at Es (react-dom.production.min.js:286:111)
    at Ca (react-dom.production.min.js:283:409)
    at Oa (react-dom.production.min.js:281:398)
    at el (react-dom.production.min.js:273:439)
    at va (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
```


For what i understood this is because grafana abandonned angular to go to react...
I tried to change the script but didn"t succeed...

**Comment by coussej** [comment]
Yeah, just checked. Seems the angular object was removed between 10.2 and 10.4. This means the foundation of this script (let's face it, was already a hack to begin with) is now gone and it's a lot more difficult to do something similar in react. 

This would mean this quick script would need to be replaced by a full blown plugin. We might come to that at some point, but it has a low priority on our development roadmap, so we need to deprecate it for now.

Happy to accept pull requests though ;-) and thanks for reporting your issue, will save others some time.

**Comment by henjoe** [comment]
Hi @coussej  is there a possibility that you will make this as plugin?

**Comment by coussej** [comment]
Unfortunately I'm not planning to work on that anytime soon.
